#
#
#

#
# Default template for the whole site.
#
template: "aktoro-site.ftlh"

#
# The home page uses a dedicated template.
#
templatesHere:
  "yawg-site-notitle.ftlh":
    - "index.html"

#
# List of globs for files NOT to be included in the bake. This list is
# tipically very similar to the .gitignore list.
#
exclude:
  - "*~"
  - "*.~"
  - "*.aux"
  - "*.bak"
  - "*.log"
  - "*.out"
  - "*.pid"
  - "target"
  - "work"
  - ".*~$"
  - ".yawg.yml"
  - ".travis.yml"
  - ".gitignore"


pageVars:
  latestAktoroVersion: 0.0.1
  navbarSelectedItem: "home"


pageVarsHere:
  breadcrumb:
    title: "Home"
    url: "index.html"

